name: qtechy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  go_router: ^15.1.1
  cached_network_image:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  # for different flavor integration
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/language/
    - assets/app_screenshorts/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# To add custom environment variables, create a file named .env in the root of your project
# To generate the flavors, run the following command:
# flutter pub run flutter_flavorizr
flavorizr:
  ide: "vscode"
  app:
    android:
      applicationId: "com.majharulDev.qtechy"
      versionCode: 1
      versionName: "1.0.0"
      minSdkVersion: 21
      targetSdkVersion: 33
      compileSdkVersion: 33
      buildToolsVersion: "33.0.0"
    ios:
      bundleId: "com.majharulDev.qtechy"
      versionCode: 1
      versionName: "1.0.0"
  flavors:
    development:
      app:
        name: "Qtechy dev"

      android:
        applicationId: "com.majharulDev.qtechyDev"
      ios:
        bundleId: "com.majharulDev.qtechyDev"
      macos:
        bundleId: "com.majharulDev.qtechyDev"
      entrypoint: "lib/app/env/main_development.dart"
    production:
      app:
        name: "Qtechy prod"

      android:
        applicationId: "com.majharulDev.qtechyProd"
      ios:
        bundleId: "com.majharulDev.qtechyProd"
      macos:
        bundleId: "com.majharulDev.qtechyProd"
      entrypoint: "lib/app/env/main_production.dart"
